from __future__ import annotations

import argparse
import json
import re
import selectors
import shutil
import subprocess
import time
from datetime import datetime
from pathlib import Path
from typing import Any


DISPATCH_ROOT = Path("/home/tedhsu/DispatchRawdata")
GREP_BIN = Path("/usr/bin/grep")
DEFAULT_SEARCH_LIMIT = 20
EXPANDED_SEARCH_LIMIT = 80
DEFAULT_INCLUDE_GLOBS = [
    "*.cs",
    "*.json",
    "*.config",
    "*.cshtml",
    "*.asax",
    "*.ashx",
    "*.xml",
]
SQL_INCLUDE_GLOBS = ["*.sql"]
DEFAULT_EXCLUDE_DIRS = [
    ".git",
    ".vs",
    "bin",
    "build",
    "coverage",
    "obj",
    "node_modules",
    "packages",
    "TestResults",
    "graphify-out",
]
FALLBACK_ROOTS = [
    "/home/tedhsu/DispatchRawdata/RD.TGDS/DEV/TGDS-TaxiPlus/01_Code/TGDS.WebAPI",
    "/home/tedhsu/DispatchRawdata/TGDS-Dispatch-WebAPI",
    "/home/tedhsu/DispatchRawdata/DispatchRule",
    "/home/tedhsu/DispatchRawdata/RD.TGDS/DEV/TGDS/CoreServers",
]
TOKEN_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]{2,}|[\u4e00-\u9fff]{2,}")
UTF16_BOMS = (b"\xff\xfe", b"\xfe\xff")


def _now_iso() -> str:
    return datetime.now().astimezone().isoformat(timespec="seconds")


def _dedupe(values: list[str]) -> list[str]:
    result: list[str] = []
    seen: set[str] = set()
    for value in values:
        key = value.lower()
        if key in seen:
            continue
        seen.add(key)
        result.append(value)
    return result


def _json_error(message: str, *, query: str = "", patterns: list[str] | None = None) -> dict[str, Any]:
    return {
        "query": query,
        "patterns": patterns or [],
        "roots": [],
        "matches": [],
        "total_count": 0,
        "truncated": False,
        "errors": [message],
        "searched_at": _now_iso(),
    }


def extract_query_patterns(query: str, *, limit: int = 8) -> list[str]:
    """Split text into lexical grep patterns for diagnostics only.

    This helper does not do semantic expansion. Normal Slack/Hermes query
    flows should pass explicit ``--pattern`` values generated by the outer LLM.
    """
    patterns = [match.group(0) for match in TOKEN_RE.finditer(query)]
    return _dedupe(patterns)[:limit]


def _repo_roots_from_config(wiki_root: Path) -> list[str]:
    repos_path = wiki_root / "Wiki" / "_meta" / "repo_sync" / "repos.json"
    try:
        data = json.loads(repos_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return []
    roots: list[str] = []
    for repo in data.get("repos") or []:
        root = str(repo.get("repoRoot") or "").strip()
        if root:
            roots.append(root)
    return roots


def _resolve_root(root_text: str) -> Path | None:
    try:
        root = Path(root_text).expanduser()
        if not root.is_absolute():
            root = DISPATCH_ROOT / root
        root = root.resolve()
        dispatch_root = DISPATCH_ROOT.resolve()
    except OSError:
        return None
    if root == dispatch_root or dispatch_root in root.parents:
        return root
    return None


def resolve_search_roots(wiki_root: Path, roots: list[str] | None = None) -> tuple[list[Path], list[str]]:
    errors: list[str] = []
    raw_roots = roots or _repo_roots_from_config(wiki_root) or FALLBACK_ROOTS
    resolved: list[Path] = []
    seen: set[str] = set()
    for raw in raw_roots:
        root = _resolve_root(str(raw))
        if root is None:
            errors.append(f"root outside allowed source tree: {raw}")
            continue
        if not root.exists():
            errors.append(f"root does not exist: {root}")
            continue
        key = str(root)
        if key in seen:
            continue
        seen.add(key)
        resolved.append(root)
    return resolved, errors


def _grep_binary() -> str | None:
    if GREP_BIN.exists():
        return str(GREP_BIN)
    return shutil.which("grep")


def _grep_args(pattern: str, root: Path, *, regex: bool, include_sql: bool = False) -> list[str]:
    args = [
        _grep_binary() or "grep",
        "-RInI",
        "-E" if regex else "-F",
    ]
    include_globs = list(DEFAULT_INCLUDE_GLOBS)
    if include_sql:
        include_globs.extend(SQL_INCLUDE_GLOBS)
    for glob in include_globs:
        args.append(f"--include={glob}")
    for directory in DEFAULT_EXCLUDE_DIRS:
        args.append(f"--exclude-dir={directory}")
    args.extend(["--", pattern, str(root)])
    return args


def _parse_grep_line(line: str) -> tuple[str, int, str] | None:
    parts = line.rstrip("\n").split(":", 2)
    if len(parts) != 3 or not parts[1].isdigit():
        return None
    return parts[0], int(parts[1]), parts[2]


def _run_grep(
    pattern: str,
    root: Path,
    *,
    regex: bool,
    include_sql: bool,
    remaining_limit: int,
    timeout_seconds: float,
) -> tuple[list[dict[str, Any]], bool, str | None]:
    grep = _grep_binary()
    if not grep:
        return [], False, "grep is not available"

    started = time.monotonic()
    proc = subprocess.Popen(
        _grep_args(pattern, root, regex=regex, include_sql=include_sql),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    selector = selectors.DefaultSelector()
    assert proc.stdout is not None
    selector.register(proc.stdout, selectors.EVENT_READ)

    matches: list[dict[str, Any]] = []
    truncated = False
    error: str | None = None
    timed_out = False

    while True:
        if len(matches) >= remaining_limit:
            truncated = True
            proc.terminate()
            break
        if time.monotonic() - started > timeout_seconds:
            timed_out = True
            proc.terminate()
            break
        if proc.poll() is not None:
            break

        events = selector.select(timeout=0.2)
        for key, _ in events:
            line = key.fileobj.readline()
            if not line:
                continue
            parsed = _parse_grep_line(line)
            if not parsed:
                continue
            path, line_number, text = parsed
            matches.append(
                {
                    "pattern": pattern,
                    "path": path,
                    "line": line_number,
                    "text": text[:500],
                }
            )
            if len(matches) >= remaining_limit:
                truncated = True
                proc.terminate()
                break

    try:
        _, stderr = proc.communicate(timeout=2)
    except subprocess.TimeoutExpired:
        proc.kill()
        _, stderr = proc.communicate(timeout=2)
    finally:
        selector.close()

    if timed_out:
        error = f"grep timed out after {timeout_seconds:.0f}s for pattern '{pattern}' under {root}"
    elif proc.returncode not in (0, 1, -15) and not matches:
        error = (stderr or f"grep failed with exit code {proc.returncode}").strip()

    return matches, truncated, error


def _path_is_excluded(path: Path) -> bool:
    return any(part in DEFAULT_EXCLUDE_DIRS for part in path.parts)


def _read_utf16_text(path: Path) -> str | None:
    try:
        raw = path.read_bytes()
    except OSError:
        return None
    if not raw.startswith(UTF16_BOMS):
        return None
    try:
        return raw.decode("utf-16")
    except UnicodeError:
        return None


def _run_utf16_sql_scan(
    pattern: str,
    root: Path,
    *,
    regex: bool,
    remaining_limit: int,
    timeout_seconds: float,
) -> tuple[list[dict[str, Any]], bool, str | None]:
    """Supplement grep for SQL Server schema files exported as UTF-16.

    GNU grep with ``-I`` intentionally skips binary-looking files, and SQL
    Server schema dumps often have UTF-16 BOMs. Without this pass, important
    table/SP evidence can look absent even when it is present in ``*.sql``.
    """
    started = time.monotonic()
    matches: list[dict[str, Any]] = []
    truncated = False
    compiled: re.Pattern[str] | None = None
    if regex:
        try:
            compiled = re.compile(pattern)
        except re.error as exc:
            return [], False, f"invalid regex for UTF-16 SQL scan: {exc}"

    try:
        sql_files = root.rglob("*.sql")
        for path in sql_files:
            if len(matches) >= remaining_limit:
                truncated = True
                break
            if time.monotonic() - started > timeout_seconds:
                return matches, truncated, f"UTF-16 SQL scan timed out after {timeout_seconds:.0f}s for pattern '{pattern}' under {root}"
            if _path_is_excluded(path):
                continue
            text = _read_utf16_text(path)
            if text is None:
                continue
            for line_number, line in enumerate(text.splitlines(), start=1):
                if compiled.search(line) if compiled is not None else pattern in line:
                    matches.append(
                        {
                            "pattern": pattern,
                            "path": str(path),
                            "line": line_number,
                            "text": line[:500],
                            "encoding": "utf-16",
                        }
                    )
                    if len(matches) >= remaining_limit:
                        truncated = True
                        break
    except OSError as exc:
        return matches, truncated, f"UTF-16 SQL scan failed under {root}: {exc}"

    return matches, truncated, None


def search_source(
    *,
    wiki_root: Path,
    query: str = "",
    patterns: list[str] | None = None,
    roots: list[str] | None = None,
    limit: int = DEFAULT_SEARCH_LIMIT,
    regex: bool = False,
    include_sql: bool = False,
    timeout_seconds: float = 45.0,
) -> dict[str, Any]:
    clean_patterns = _dedupe([p.strip() for p in (patterns or []) if p.strip()])
    if not clean_patterns and query.strip():
        clean_patterns = [query.strip()]
    if not clean_patterns:
        return _json_error("no search patterns provided", query=query, patterns=[])

    limit = max(1, min(int(limit), 200))
    wiki_root = wiki_root.resolve()
    search_roots, errors = resolve_search_roots(wiki_root, roots)
    if not search_roots:
        result = _json_error("no valid source roots", query=query, patterns=clean_patterns)
        result["errors"].extend(errors)
        return result

    matches: list[dict[str, Any]] = []
    truncated = False
    for pattern in clean_patterns:
        if len(matches) >= limit:
            truncated = True
            break
        for root in search_roots:
            if len(matches) >= limit:
                truncated = True
                break
            found, did_truncate, error = _run_grep(
                pattern,
                root,
                regex=regex,
                include_sql=include_sql,
                remaining_limit=limit - len(matches),
                timeout_seconds=timeout_seconds,
            )
            matches.extend(found)
            truncated = truncated or did_truncate
            if error:
                errors.append(error)
            if len(matches) >= limit:
                truncated = True
                break
            if include_sql:
                found, did_truncate, error = _run_utf16_sql_scan(
                    pattern,
                    root,
                    regex=regex,
                    remaining_limit=limit - len(matches),
                    timeout_seconds=timeout_seconds,
                )
                matches.extend(found)
                truncated = truncated or did_truncate
                if error:
                    errors.append(error)

    return {
        "query": query,
        "patterns": clean_patterns,
        "roots": [str(root) for root in search_roots],
        "matches": matches,
        "total_count": len(matches),
        "truncated": truncated,
        "errors": errors,
        "searched_at": _now_iso(),
        "limit_policy": {
            "default_limit": DEFAULT_SEARCH_LIMIT,
            "expanded_limit": EXPANDED_SEARCH_LIMIT,
            "expand_when": (
                "Only raise --limit after the first pass returns relevant but incomplete evidence; "
                "for broad/common patterns, refine roots or patterns before expanding."
            ),
        },
        "search_contract": {
            "engine": _grep_binary() or "grep",
            "fixed_string_default": not regex,
            "include_globs": list(DEFAULT_INCLUDE_GLOBS) + (SQL_INCLUDE_GLOBS if include_sql else []),
            "include_sql": include_sql,
            "multi_keyword_strategy": "one grep call per pattern",
            "semantic_expansion": "none; caller must provide explicit patterns",
            "utf16_sql_scan": "enabled only when include_sql=true",
            "allowed_source_root": str(DISPATCH_ROOT),
        },
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Deterministic source search for LLM Wiki queries")
    parser.add_argument("--wiki-root", default=".", help="Path to llm-wiki root")
    parser.add_argument("--query", default="", help="Legacy literal pattern used only when --pattern is absent")
    parser.add_argument("--pattern", action="append", default=[], help="Fixed-string search pattern; may repeat")
    parser.add_argument("--root", action="append", default=[], help="Source root under /home/tedhsu/DispatchRawdata; may repeat")
    parser.add_argument(
        "--limit",
        type=int,
        default=DEFAULT_SEARCH_LIMIT,
        help=(
            f"Maximum total matches (default {DEFAULT_SEARCH_LIMIT}; use "
            f"{EXPANDED_SEARCH_LIMIT} only after a relevant but incomplete first pass)"
        ),
    )
    parser.add_argument("--regex", action="store_true", help="Use grep -E instead of fixed-string grep -F")
    parser.add_argument(
        "--include-sql",
        action="store_true",
        help="Opt in to *.sql and UTF-16 SQL schema scans; default searches source code/config only.",
    )
    parser.add_argument("--json", action="store_true", help="Print JSON output")
    args = parser.parse_args(argv)

    result = search_source(
        wiki_root=Path(args.wiki_root),
        query=args.query,
        patterns=args.pattern,
        roots=args.root,
        limit=args.limit,
        regex=args.regex,
        include_sql=args.include_sql,
    )
    if args.json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        print(f"matches: {result['total_count']}")
        for match in result["matches"]:
            print(f"{match['path']}:{match['line']}:{match['text']}")
        if result["errors"]:
            print("errors:")
            for error in result["errors"]:
                print(f"- {error}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
